import { useContext } from 'react'
import { useReducer } from 'react'
import { loginReducer, todoReducer } from '@/state/reducer'
import { MainContext } from '@/state/global'
import { initialState } from '@/state/global'
import Head from 'next/head'
import Navbar from '@/components/navbar'


export default function Login() {
  const [state, dispatch] = useReducer(loginReducer, initialState);

  
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainContext.Provider value={{state, dispatch}}>
        <main >
          <Navbar />
          <h1>LoginPage</h1>

          
        </main>  
      </MainContext.Provider>
       
    </>
  )
}
